apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-temporal.fullname" . }}-trigger-server
  labels:
    {{- include "job-temporal.labels" . | nindent 4 }}
    app.kubernetes.io/component: trigger-server
spec:
  {{- if not .Values.triggerServer.autoscaling.enabled }}
  replicas: {{ .Values.triggerServer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "job-temporal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: trigger-server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "job-temporal.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: trigger-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "job-temporal.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: trigger-server
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.triggerServer.image.repository }}:{{ .Values.triggerServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.triggerServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          env:
            - name: TEMPORAL_ADDRESS
              value: {{ .Values.temporalAddress | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "job-temporal.sharedSecretName" . }}
                  key: DATABASE_URL
          {{- with .Values.triggerServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.triggerServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.triggerServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
