{{- if .Values.triggerServer.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "job-temporal.fullname" . }}-trigger-server
  labels:
    {{- include "job-temporal.labels" . | nindent 4 }}
    app.kubernetes.io/component: trigger-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "job-temporal.fullname" . }}-trigger-server
  minReplicas: {{ .Values.triggerServer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.triggerServer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.triggerServer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.triggerServer.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.triggerServer.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.triggerServer.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
