{{- if .Values.temporal.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-temporal.fullname" . }}-temporal
  labels:
    {{- include "job-temporal.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "job-temporal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: temporal
  template:
    metadata:
      {{- with .Values.temporal.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "job-temporal.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: temporal
    spec:
      serviceAccountName: {{ include "job-temporal.serviceAccountName" . }}
      {{- with .Values.temporal.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: temporal
          {{- with .Values.temporal.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.temporal.image.repository }}:{{ .Values.temporal.image.tag }}"
          imagePullPolicy: {{ .Values.temporal.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 7233
              protocol: TCP
          env:
            - name: DB
              value: {{ .Values.temporal.db | quote }}
            - name: DB_PORT
              value: {{ .Values.temporal.dbPort | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ required "existingSecret.temporal.name is required" .Values.existingSecret.temporal.name | quote }}
                  key: {{ .Values.existingSecret.temporal.postgresUserKey | quote }}
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.temporal.name | quote }}
                  key: {{ .Values.existingSecret.temporal.postgresPwdKey | quote }}
            - name: POSTGRES_SEEDS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.temporal.name | quote }}
                  key: {{ .Values.existingSecret.temporal.postgresSeedsKey | quote }}
          {{- with .Values.temporal.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.temporal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.temporal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.temporal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
