{{- if .Values.temporalUI.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "job-temporal.fullname" . }}-temporal-ui
  labels:
    {{- include "job-temporal.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-ui
spec:
  type: {{ .Values.temporalUI.service.type }}
  ports:
    - port: {{ .Values.temporalUI.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "job-temporal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-ui
{{- end }}
